# Generated by Django 3.2.24 on 2024-08-30 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='adddate',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
