# Generated by Django 3.2.24 on 2024-08-30 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_book_adddate'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='registerationdate',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
