# Generated by Django 5.1 on 2024-09-01 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_book_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='isbn',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
